jobin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('consultants.urls'), name='consultants_urls'),
    path('accounts/', include('allauth.urls')),
]

consultants/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from cloudinary.models import CloudinaryField


class User(AbstractUser):
    """
    Create custom user as customer or partner
    """

    CHOICES = ((0, 'Customer'), (1, 'Partner'))

    user_type = models.IntegerField(choices=CHOICES, default=0)
    company = models.CharField(max_length=100, default='Company')
    vat_no = models.CharField(max_length=50, default='0')
    phone = models.IntegerField(default=0)

    def __str__(self):
        return self.username


# Set status of request if it is active or not due to deadline
STATUS = ((0, 'Active'), (1, 'Inactive'))


class Order(models.Model):
    """
    Data that is being stored for every order created
    """
    title = models.CharField(max_length=200)
    role = models.CharField(max_length=50)
    period = models.CharField(max_length=50)
    startdate = models.DateField()
    locality = models.CharField(max_length=50)
    duties = models.TextField()
    requirements = models.TextField()
    wishes = models.TextField()
    deadline = models.DateField()
    responsible = models.ForeignKey(
        User,
        on_delete=models.CASCADE, related_name='consultant_request')
    created_date = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return self.title


class Candidate(models.Model):
    """
    Model for partners to present candidates
    """
    first_name = models.CharField(max_length=50)
    summary = models.CharField(max_length=200)
    price = models.CharField(max_length=50)
    cv = CloudinaryField('cv')
    offer = CloudinaryField('offer')
    manager = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='presented_candidates')
    presented_date = models.DateField(auto_now_add=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, default="")

    class Meta:
        ordering = ['presented_date', 'manager']

    def __str__(self):
        return f'Candidate {self.first_name} presented by {self.manager}'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description"
    content="Are you in need of a consultant? Compare and find the best consultant for your company, 100% free of charge.">
  <meta name="keywords" content="Consultant, find consultant, compare consultant, it consultant, cheap consultant">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Find and compare the best consultants for your company</title>
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg position-relative">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">JobIn</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
        aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 200px;">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home <span
                class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#why-use-us">Why Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#step-by-step">Step-by-step</a>
          </li>
        </ul>
        <!-- Display navbar links for logged in Customers -->
        {% if user.is_authenticated %}
        {% if user.user_type == 0 %}
        <ul class="navbar-nav end-0 mx-3 nav-logedin">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user/overview' %}">Your Requests</a>
          </li>
        </ul>
          <a class="btn btn-outline-success my-2 my-sm-0 custom-button" href="{% url 'account_logout' %}">Logout</a>
          
          {% endif %}
          <!-- Display navbar links for logged in Partners -->
          {% if user.user_type == 1 %}
          <ul class="navbar-nav end-0 mx-3 nav-logedin">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'overview' %}">Overview</a>
            </li>
          </ul>
            <a class="btn btn-outline-success my-2 my-sm-0 custom-button" href="{% url 'account_logout' %}">Logout</a>
            {% endif %}
            {% else %}
            <a href="{% url 'account_login' %}" class="link-in-button btn btn-outline-success my-2 my-sm-0 custom-button">Login/Register</a>
            {% endif %}
      </div>
    </div>
  </nav>

  <!-- Messages to user -->
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 text-center">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
          {{ message | safe }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <main class="flex-shrink-0 main-bg">
    {% block content %}
    <!-- Content -->
    {% endblock content %}
  </main>

<!-- Back to top button -->
<button type="button" class="btn btn-danger btn-floating" onclick="toTheTop()" id="scrollbtn"><i class="fa-solid fa-arrow-up"></i></button>

<!-- Footer -->
<footer class="text-muted navbar fixed-bottom" id="showfooter">
  <div class="col-md-12 mt-4 mx-auto">
    <ul class="socials">
      <li>
        <a href="https://github.com/williamtyn" target="_blank" rel="noopener"
          aria-label="Visit developers Github page (opens in a new tab)"><i class="fa-brands fa-github"></i></a>
      </li>
      <li>
        <a href="https://linkedin.com/in/williamtyner" target="_blank" rel="noopener"
          aria-label="Visit developers LinkedIn page (opens in a new tab)"><i class="fa-brands fa-linkedin"></i></a>
      </li>
      <li>
        <a href="https://facebook.com" target="_blank" rel="noopener"
          aria-label="Visit JobIns Facebook page (opens in a new tab)"><i class="fa-brands fa-facebook"></i></a>
      </li>
    </ul>
  </div>
</footer>
<!-- Script for bootstrap and fontawesome -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/689aa347cf.js" crossorigin="anonymous"></script>
<!-- Custom script.js -->
<script src="{% static './js/script.js' %}"></script>
</body>
</html>

templates/delete_order.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12">
      <h3>Delete your request</h3>
    </div>
  </div>
  <hr>
</div>
{% if user.is_authenticated and order.responsible == request.user %}
<div class="container">
  <div class="row">
    <div class="col-md-8 mt-5 offset-md-2 text-center">
      <h3>You are about to delete this order</h3>

      <p>This will be delete permanently! Are you sure you want to delete?</p>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 mt-2 text-center">
        <form method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Confirm Delete</button>
        </form>
        <div>
          <a href="{% url 'user/overview' %}" class="btn btn-outline-dark">Cancel</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% else %}
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      This is not your request and you do not have access to this page
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

templates/edit_order.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h3>Change your request</h3>
        </div>
    </div>
    <hr>
</div>
<!-- Form for making a new order as customer -->
{% if user.is_authenticated and order.responsible == request.user %}
<div class="container">
    <div class="row">
        <form method="post" style="margin-top: 1.3em;">
            {{ form | crispy }}
            {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-success">Make Changes</button>
        </form>
        <div>
            <a href="{% url 'user/overview' %}" class="btn btn-outline-dark">Cancel</a>
        </div>
    </div>
</div>
<br>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            This is not your request and you do not have access to this page
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<!--Header with hero image-->
<header>
    <!-- Hero image -->
    <div id="hero-image" class="p-5 text-center bg-image">
        <div class="overlay">
            <div class="d-flex justify-content-center align-items-center h-100">
                <div class="text-white">
                    <h1 class="mb-3">Find and compare the best consultants</h1>
                    <h4 class="mb-4">
                        Finding the right consultant is more difficult than ever.<br>
                        That's why we've made it simple.
                    </h4>
                    <a class="btn btn-outline-light btn-lg m-2" href="{% url 'account_signup' %}" role="button">Free
                        Signup</a>
                    <a class="btn btn-outline-light btn-lg m-2" href="#steps" role="button">Read more</a>
                </div>
            </div>
        </div>
    </div>
</header>

<!--Icons with text-->
<div class="container mt-5" id="why-use-us">
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="feature col text-center">
            <div
                class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
                <i class="fa-solid fa-list-check"></i>
            </div>
            <h3 class="fs-2">The right competence</h3>
            <p>Our partners are some of the best in the world at finding the right one.
            </p>
        </div>
        <div class="feature col text-center">
            <div
                class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
                <i class="fa-regular fa-heart"></i>
            </div>
            <h3 class="fs-2">For a easier life</h3>
            <p>Our partners present their best candidates to you. You see experience, skills, terms and prices.</p>
        </div>
        <div class="feature col text-center">
            <div
                class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
                <i class="fa fa-money"></i>
            </div>
            <h3 class="fs-2">With less money</h3>
            <p>Compare and find the candidates that suit you and your business best.</p>
        </div>
    </div>
</div>
<br>
<br>

<!--Icons with text-->
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Are you in need of a consultant?</h2>
            <hr>
            <h3>The best tool in the world</h3>
            <p>There is no better way than via our tool.
                State your skill requirements and let our partners present their best candidates to you. In our tool,
                you can see experience, competence, availability and price in a very simple way.

                Then choose who you want to meet for an interview.
            </p>
            <p>
                Our application is 100% free of charge and no credit card required.
            </p>
            <br>
            <a class="btn btn-outline-success" href="{% url 'account_signup' %}" role="button">Make Free Request</a>
        </div>
        <div class="col-md-6">
            <img src="https://res.cloudinary.com/dpliee0fu/image/upload/v1669651149/mockup_overview_wuhr8a.webp" class="img-fluid"
                alt="Image showing our application on a desktop">
        </div>
    </div>
    <br>
</div>

<!--Call to action with button-->
<div class="container-fluid py-5 cta text-center">
    <div class="col-md-12 cta-overlay">
            <h3 class="display-5 ">Do you want to present your consultants?</h3>
            <a class="btn btn-outline-light btn-lg m-2" href="{% url 'account_signup' %}" role="button">Partner Signup</a>
    </div>
</div>

<!--Step By Step-->
<div class="container" id="step-by-step">
    <div class="row" id="steps">
        <div class="col-md-12 mt-5">
            <h3>Step by step how it works</h3>
            <hr>
        </div>
    </div>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="col d-flex align-items-start">
            <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
                <i class="fa-solid fa-1"></i>
            </div>
            <div>
                <h4>Fill in your requirements</h4>
                <p>
                    Sign up as a customer for free. When you have logged in, you can make your first request for what
                    kind of consultant your company is searching <br><br>
                    Specify what requirements, experience, and soft skills the consultant should have.
                </p>
            </div>
        </div>
        <div class="col d-flex align-items-start">
            <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
                <i class="fa-solid fa-2"></i>
            </div>
            <div>
                <h4>Your request goes out</h4>
                <p>
                    When your request is published, it goes out to all our partners that are connected to our service.
                    They see your request and try to match it with a consultant in their pool. When they have
                    someone who matches your requirements, they present that candidate to you with all the information
                    you need.
                </p>
            </div>
        </div>
        <div class="col d-flex align-items-start">
            <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
                <i class="fa-solid fa-3"></i>
            </div>
            <div>
                <h4>Find the right consultant</h4>
                <p>
                    Candidates are being presented to you in your overview. You can, in the comfort of your office,
                    compare the consultants against each other.
                    and decide whether or not you want to meet with any of them for an interview. Contact information
                    for their manager is also presented.
                </p>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12 mt-5 text-center">
            <p><em>“If you always do what you've always done, you'll always get what you've always got.”</em></p>
            <hr class="dividerline">
        </div>
    </div>
</div>

{%endblock%}

templates/new_candidate.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h3>Present your candidate</h3>
        </div>
    </div>
    <hr>
</div>
<!-- Form for presenting a new candidate as partner -->
{% if user.is_authenticated and user.user_type == 1 %}
<div class="container">
    <div class="row">
        <form method="post" enctype="multipart/form-data" style="margin-top: 1.3em;">
            {{ form | crispy }}
            {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-success">Send Candidate</button>
        </form>
        <div>
            <a href="{% url 'overview' %}" class="btn btn-outline-dark">Cancel</a>
        </div>
    </div>
</div>
<br>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            You need to be a partner to have access to this page
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

templates/new_order.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h3>Make a new request</h3>
        </div>
    </div>
    <hr>
</div>
<!-- Form for making a new order as customer -->
{% if user.is_authenticated and user.user_type == 0 %}
<div class="container">
    <div class="row">
        <form method="post" style="margin-top: 1.3em;">
            {{ form | crispy }}
            {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-success">Send Request</button>
        </form>
        <div>
            <a href="/user/overview" class="btn btn-outline-dark">Cancel</a>
        </div>
    </div>
</div>
<br>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            You need to be a customer to have access to this page
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

templates/orderlist.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-10">
            <h3>Active Requests</h3>
            <p>See all active requests</p>
        </div>
        <div class="col-md-2">
        </div>
    </div>
    <hr>
</div>
<!-- Showing each active order as a collapse -->
{% if user.is_authenticated and user.user_type == 1 %}
<div class="container">
    <div class="row">
        {% for order in order_list %}
        <div class="accordion" id="accordion{{ order.id }}">
            <!-- Order header/titel -->
            <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ order.id }}">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#ord{{ order.id }}" aria-expanded="true" aria-controls="ord{{ order.id }}">
                        {{ order.title }}
                    </button>
                </h2>
            </div>
            <!-- Order body -->
            <div id="ord{{ order.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ order.id }}"
                data-bs-parent="#accordion{{ order.id }}">
                <div class="container accordion-body">
                    <div class="row">
                        <div class="col-sm-6 col-md-2">
                            <h5>Role</h5>
                            {{ order.role }}
                        </div>
                        <div class="col-sm-6 col-md-2">
                            <h5>Period</h5>
                            {{ order.period }}
                        </div>
                        <div class="col-sm-6 col-md-2">
                            <h5>Startdate</h5>
                            {{ order.startdate }}
                        </div>
                        <div class="col-sm-6 col-md-2">
                            <h5>City</h5>
                            {{ order.locality }}
                        </div>
                        <div class="col-sm-6 col-md-2">
                            <h5>Deadline</h5>
                            {{ order.deadline }}
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-12 col-md-4">
                            <h5>Duties</h5>
                            {{ order.duties }}
                        </div>
                        <div class="col-sm-12 col-md-4">
                            <h5>Requirements</h5>
                            {{ order.requirements }}
                        </div>
                        <div class="col-sm-12 col-md-4">
                            <h5>Wishes</h5>
                            {{ order.wishes }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 text-center">
                            <br>
                            <a href="{% url 'new-candidate' %}" class="btn btn-success">Send
                                    Candidate</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            You need to be a partner to have access to this page
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

templates/user_orderlist.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load static %}
{% block content %}

<div class="container mt-5">
  <div class="row">
    <div class="col-md-10">
      <h3>Your Request Overview</h3>
      <p>Manage your active requests</p>
      {% if user.is_authenticated and user.user_type == 0 %}
    </div>
    <div class="col-md-2">
      <br>
      <a href="{% url 'new/order' %}" class="btn btn-success">New Request</a>
    </div>
  </div>
  <hr>
</div>
<!-- Showing each customer order as a collapse -->
<div class="container">
  {% for order in user_orders %}
  <div class="row">

    <div class="accordion" id="accordion{{ order.id }}">
      <div class="accordion-item">
        <!-- Order header/titel -->
        <h2 class="accordion-header" id="heading{{ order.id }}">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#order{{ order.id }}"
            aria-expanded="true" aria-controls="order{{ order.id }}">
            {{ order.title }}
          </button>
        </h2>
      </div>
      <!-- Order body -->
      <div id="order{{ order.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ order.id }}"
        data-bs-parent="#accordion{{ order.id }}">
        <div class="container accordion-body">
          <div class="row">
            <div class="col-sm-6 col-md-2">
              <h5>Role</h5>
              {{ order.role }}
            </div>
            <div class="col-sm-6 col-md-2">
              <h5>Period</h5>
              {{ order.period }}
            </div>
            <div class="col-sm-6 col-md-2">
              <h5>Startdate</h5>
              {{ order.startdate }}
            </div>
            <div class="col-sm-6 col-md-2">
              <h5>City</h5>
              {{ order.locality }}
            </div>
            <div class="col-sm-6 col-md-2">
              <h5>Deadline</h5>
              {{ order.deadline }}
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-sm-12 col-md-4">
              <h5>Duties</h5>
              {{ order.duties }}
            </div>
            <div class="col-sm-12 col-md-4">
              <h5>Requirements</h5>
              {{ order.requirements }}
            </div>
            <div class="col-sm-12 col-md-4">
              <h5>Wishes</h5>
              {{ order.wishes }}
            </div>
          </div>
          <!-- Buttons for edit and deleting Order -->
          <div class="row">
            <div class="col-12 text-center">
              <br>
              <a href="/edit/{{ order.id }}" class="btn btn-outline-success">Edit Request</a>
              <a href="/delete/{{ order.id }}" class="btn btn-outline-danger">Delete</a>
            </div>
          </div>
        </div>
        <br>
        <hr class="dividerline">
        <br>
        <!-- Showing each candidate presented from Partner -->
        <div class="col-12 text-center">
          <h5>Candidates</h5>
          <button type="button" onclick="toggleCandidates(event)" class="btn btn-outline-success">Show
            Candidates</button>
          <br>
          <br>
        </div>
        <div class="row toggle">
          <!-- Check if model have any candidates presented otherwise displaying else statement -->
          {% if order.candidate_set.all.count > 0 %}
          {% for candidate in order.candidate_set.all %}
          <div class="col-sm-12 col-md-4 text-center">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ candidate.first_name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ candidate.price }}</h6>
                <p class="card-text">{{ candidate.summary }}</p>
                <a href="{{ candidate.cv.url }}" target="_blank" class="btn btn-success card-link">See CV</a>
                <a href="{{ candidate.offer.url }}" target="_blank" class="btn btn-outline-success card-link">See
                  Offer</a>
                <a href="mailto:{{ candidate.manager.email }}" class="btn btn-outline-dark card-link">Contact
                  Manager</a>
              </div>
            </div>
          </div>
          <br>
          {% endfor %}
          <!-- Showing message if no candidates have been presented -->
          {% else %}
          <div class="row">
            <p class="text-center"><i>You do not have any presented candidates on this request</i></p>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      You need to be a customer to have access to this page
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}